os: linux
sudo: required
language: "minimal"
services:
- docker

before_script:
  - docker pull toliak/bootstrap-cpp

jobs:
  include:
    - name: "checks"
      script:
       ./scripts/checks.sh toliak/bootstrap-cpp
    - name: "tests"
      script:
       ./scripts/tests.sh toliak/bootstrap-cpp 
    - name: "quality"
      script:
        ./scripts/duplication.sh toliak/bootstrap-cpp 

notifications:
    email: false



